POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "The Lion, The Witch, and the Wardrobe",
    "author": "C.S. Lewis",
    "url": "www.test.com",
    "likes":0
}