POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndqZGl0dG1hcjQiLCJpZCI6IjY2MDFmYWE0NjdiZmEzYjIzYWQ1ZWY3YiIsImlhdCI6MTcxMTQwNzMxNX0.awXiXRSLda1NWlDJTDeNrHVMEyAgkyB5tWtZxkPRnT4

{
    "title": "The Lion, The Witch, and the Wardrobe",
    "author": "C.S. Lewis",
    "url": "www.test.com",
    "likes":0
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "First class tests",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
    "likes": 10
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Canonical string reduction",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 12
}